CREATE TABLE `fund` (
 `Id` int(11) NOT NULL AUTO_INCREMENT,
 `Name` varchar(256) NOT NULL,
 PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
CREATE TABLE `rate` (
 `Id` int(11) NOT NULL AUTO_INCREMENT,
 `Date` date NOT NULL,
 `Value` decimal(10,2) NOT NULL,
 `LastUpdate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
 `FundId` int(11) NOT NULL,
 PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8